### ISSUE TITLE
Generate the html/pdf versions corresponding to this project.

### ISSUE THREAD

**Issue by hongyi-zhao** [sean-fitzpatrick/Math3410#3]
Dear Dr. Sean Fitzpatrick,

I noticed [your lecture notes for Math 3410](https://opentext.uleth.ca/Math3410/linear-algebra.html) in [PreTeXt](https://github.com/rbeezer/mathbook) on the Open Math Textbooks website [here](https://opentext.uleth.ca/linalg.html). 

I also noted that you provided the following versions for this course: [HTML version, with interactive code cells](https://opentext.uleth.ca/Math3410/), [PDF e-book (aligns with HTML version)](https://opentext.uleth.ca/PDF/3410notes-ebook.pdf), and [PreTeXt-generated PDF, optimized for printing](https://opentext.uleth.ca/PDF/3410notes-print.pdf). Furthermore, I also find the corresponding [style files](https://github.com/sean-fitzpatrick/Math3410/tree/class/style) for building the above versions, but I still can't figure out the detailed steps/commands used by you to create these versions based on this github repo.

Any hints will be highly appreciated.

Regards,
HY

**Comment by sean-fitzpatrick** [comment]
You can point to those style sheets instead of whatever pretext style sheet you'd normally use. (E.g. replace pretext-latex.html in your build command with the html style file.)

**Comment by hongyi-zhao** [comment]
According to your notes above, I tried some alternative methods, but they all failed. See [here](https://groups.google.com/g/pretext-support/c/zaBq7BZ_HeE/m/WdyLc_EmBAAJ) for more detailed info.

**Comment by sean-fitzpatrick** [comment]
Sorry -- forgot an additional detail. You need to copy (or symlink) these into the folder where your pretext xsl files live, and run from there

**Comment by hongyi-zhao** [comment]
Your above description is inconsistent with the following notes give by [Rob Beezer](https://groups.google.com/g/pretext-support/c/zaBq7BZ_HeE/m/_uhoXOVDBAAJ):

```
I suspect Sean's extra XSL needs to live in a *new*

./user

that you should create. That's where we put a customized pretext.cfg so it is
not tracked by the git repository.
```

And furthermore, I also noticed the following notes give by [the official documentation](https://pretextbook.org/doc/guide/html/pretext-helpers.html):

```
cd /path/to/mathbook
mkdir user
cp pretext/pretext.cfg user/
```

The pretext.cfg mentioned above can be found [here](https://github.com/rbeezer/mathbook/blob/dev/pretext/pretext.cfg).

Any further comment/reassurance/confirmation will be highly/greatly appreciated.

Regards,
HY

**Comment by sean-fitzpatrick** [comment]
I have provided you with my exact folder structure on the PreTeXt forum. You should be able to work out how to adapt that to your own folder structure.
